file=open("example.txt",'r')
content=file.read()
print(content)
file.close()
file=open("example.txt","a")
file.write("\n welcome to this world\n")
file.close()
file=open("example.txt",'r')
rline=file.readline()
print(rline)
file.close()
